#!/bin/bash
function go_docker {
	DOCKER_NAME="docker-proxy-acl"
	if [ "$(docker ps -a |grep -c $DOCKER_NAME)" = "1" ]; then
        	echo "$DOCKER_NAME already exist, stop and remove"
		docker stop $DOCKER_NAME && docker rm $DOCKER_NAME
	fi

	ARGS=""
	if [ -f "docker.args" ]; then
		ARGS=$(cat docker.args | xargs echo -n)
	fi

	docker run --name=$DOCKER_NAME $ARGS -v `pwd`:/go/src/app -w /go/src/app golang go "$@"
}

function go_fetch {
	BASE="vendor/"
	if [ ! -d "$BASE$1" ]; then
		echo "Fetching: $1"
		gvt fetch $1
	fi
}

go_fetch github.com/namsral/flag
go_fetch github.com/gorilla/mux

go_docker run docker-proxy-acl.go "$@"
